apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-volume
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: secret-volume
          mountPath: "/mnt/secrets"
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret
          items:
          - key: user
            path: postgres/username
          - key: password
            path: postgres/password
  
