apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: macborowy/chmurobank-api:latest
        name: app
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: backend
spec:
  type: ClusterIP
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: api