apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker
  namespace: backend
spec:
  jobTemplate:
    metadata:
      name: worker
    spec:
      template:
        spec:
          initContainers:
          - name: sync-secrets
            image: busybox
            command: ['sh', '-c', 'until ls ./mnt/secrets-store; do echo Waiting for secrets to sync && sleep 1; done']
            volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          containers:
          - image: macborowy/chmurobank-exchangerates-downloader
            name: worker
            envFrom:
            - secretRef:
                name: db-secrets
          volumes:
          - name: secrets-store-inline
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "azure-kvname"
          restartPolicy: OnFailure
  schedule: "0 5 * * *"
