version: "3.9"
services:
  frontend:
    build:
      context: ./packages/frontend
    ports:
    - "8080:80"
    environment:
    - "API_URL=http://localhost:8888"
  api:
    build:
      context: ./packages/api
    ports:
    - "8888:8888"
