apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: danchmpis/chm-k8s-namespace-backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: backend-svc
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend

