apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  labels:
    test: livenessProbe
spec:
  containers:
  - name: liveness
    image: danchmpis/chm-k8s-probe:latest
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 2