apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-azure-database-connection-details
data:
  PGUSER: "postgres"
  PGHOST: "psql-cm-test.postgres.database.azure.com"
  PGPASSWORD: "Chmurowisko123"
  PGDATABASE: "test"
  PGPORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: app
        image: macborowy/azure-database-psql
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: cm-azure-database-connection-details
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: api
  type: LoadBalancer
