apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout
  labels:
    app: rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollout
  template:
    metadata:
      labels:
        app: rollout
    spec:
      containers:
      - name: app
        image: macborowy/workshop-rollout:1.0.0
        ports:
        - containerPort: 8080